### ISSUE TITLE
(bug) YouTube 2.1.6 patched with yt2009 (yt2009.org, patched by u/ExtremeDumbGuy) is broken.

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#61] opened 2024-03-16 15:53 UTC
I'm not sure why, and it's not my patch (it was by u/ExtremeDumbGuy), the YouTube 2.1.6 patched apk with yt2009.org is not working for some reason.

The reason is: **Maybe it was patched incorrectly or the yt2009 was on a different port, idk...**

I downloaded the apk from his Google Drive and installed it normally.
The homepage, search page, channel page, some of these work nicely.
But videos don't play, sign in **"works"**, but it's just a trick and will say that I "don't have" a YouTube account (will not sign in).
Can't see related videos or comments, profile pictures, and also can't view videos from any playlist...

Right now, this is pretty much useless as far as I know.
To look more in detail, here are some images and the apk with the broken app.

![Screenshot_2024 03 16_17 45 52 389](https://github.com/ftde0/yt2009/assets/110676833/55a2ba87-b4f0-46a8-b26e-445a42575f39)
![Screenshot_2024 03 16_17 47 46 023](https://github.com/ftde0/yt2009/assets/110676833/2c8cdfd1-d726-4af7-9952-61fba2726ebb)
![Screenshot_2024 03 16_17 47 49 140](https://github.com/ftde0/yt2009/assets/110676833/4eec0370-c720-4ca4-b8c0-31595e0b18c5)
![Screenshot_2024 03 16_17 47 53 439](https://github.com/ftde0/yt2009/assets/110676833/810e4633-0ecd-4679-bed0-fa1d15d1c5cc)
![Screenshot_2024 03 16_17 47 58 055](https://github.com/ftde0/yt2009/assets/110676833/50e65ee5-143c-404d-82a2-0552e3617fb0)
![Screenshot_2024 03 16_17 48 34 124](https://github.com/ftde0/yt2009/assets/110676833/d4745466-90bf-4d13-8913-fdd9769c28b6)
[YoutubePatchwithYT2009org.zip](https://github.com/ftde0/yt2009/files/14624247/YoutubePatchwithYT2009org.zip)

Can you look into this, and if so, is there any fix for this? Thank you @ftde0 .

**Comment by breakgimme** [comment] 2024-03-16 17:56
this is issue is a duplicate of #58 and was already fixed here
yt2009.org is outdated by a few versions so it doesn't have the fix yet

**Comment by mrkrabs206** [comment] 2024-03-16 19:26
> this is issue is a duplicate of #58 and was already fixed here yt2009.org is outdated by a few versions so it doesn't have the fix yet

ok

**Closed** 2024-03-16 19:36 UTC
