### ISSUE TITLE
cpb.swf doesn't have annotations or captions working, and can't even turn on annotations on late 2009-mid 2010 players (nothing happens when clicked)

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#133] opened 2024-09-01 10:35 UTC
For some reason, the playlists player (cpb.swf) doesn't really have the ability to use captions or annotations (at the moment at least...).
Like this:

https://github.com/user-attachments/assets/543a2fa5-f803-40c0-8d31-3df22abea2da

(http://192.168.0.192:80/alt-swf/cpb.swf?player_id=1Aetq1LjgtQ&datatype=playlist&data=PLIl2EzNYri0crmY28ZNs-bsgzGOms2nAn&BASE_YT_URL=http://192.168.0.192:80/)

Even with forced subtitle_module and iv_module, nothing seems to work.

And regarding that, for late2009-mid2010 players, the annotations button does nothing.:

https://github.com/user-attachments/assets/911a0f92-c905-4836-aed9-d6ce75218255

When will you fix it? Do you have something to make it work on cpb and fix the annotations button? Thank you.

**Comment by ftde0** [comment] 2024-09-02 11:52
you're the one mismatching all the random players and modules and expecting **me** to fix that. basically a duplicate of #122. wait for the next update that will add specifying custom as2 modules for watch.

**Closed by ftde0** 2024-09-02 11:52 UTC

**Comment by gigigigi53** [comment] 2024-09-15 17:26
> you're the one mismatching all the random players and modules and expecting **me** to fix that. basically a duplicate of #122. wait for the next update that will add specifying custom as2 modules for watch.

I seriously apologize
